In [1]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np

In [4]:
#Load the ANN trained model,scaler pickle, onehot
model=load_model('model.h5')

#load the encoder and scaler
with open('label_encoder_gender','rb') as file:
    label_encoder_gender=pickle.load(file)

with open('scaler.pkl','rb') as file:
    scaler=pickle.load(file)

with open('ohe_geo','rb') as file:
    ohe_geo=pickle.load(file)

In [6]:
#Example input data
input_data={
    'CreditScore':600,
    'Geography':'France',
    'Gender':'Male',
    'Age':40,
    'Tenure':3,
    'Balance':60000,
    'NumOfProducts':2,
    'HasCrCard':1,
    'IsActiveMember':1,
    'EstimatedSalary':50000
}

#first u need to convert the categorical variables into numerical

In [7]:
#one hot encode Geography
geo_encoded=ohe_geo.transform([[input_data['Geography']]]).toarray()
geo_encoded

c:\Users\Srees_lappy\Desktop\dscodes\My_practice\53_project_ann\venv53\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[1., 0., 0.]])

In [8]:
geo_encoded_df=pd.DataFrame(geo_encoded,columns=ohe_geo.get_feature_names_out(['Geography']))
geo_encoded_df

Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [ ]:
input_data=pd.DataFrame([input_data])

In [11]:
input_data

CreditScore Geography Gender  Age  Tenure  Balance  NumOfProducts  \
0          600    France   Male   40       3    60000              2   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1            50000

In [ ]:
#encode cat column Gender
input_data.Gender=label_encoder_gender.transform(input_data.Gender)

In [13]:
input_data

CreditScore Geography  Gender  Age  Tenure  Balance  NumOfProducts  \
0          600    France       1   40       3    60000              2   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1            50000

In [ ]:
#concat onehot encoded geography
input_df=pd.concat([input_data.drop(['Geography'],axis=1),geo_encoded_df],axis=1)

CreditScore Geography  Gender  Age  Tenure  Balance  NumOfProducts  \
0          600    France       1   40       3    60000              2   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1            50000

In [15]:
input_df

CreditScore  Gender  Age  Tenure  Balance  NumOfProducts  HasCrCard  \
0          600       1   40       3    60000              2          1   

   IsActiveMember  EstimatedSalary  Geography_France  Geography_Germany  \
0               1            50000               1.0                0.0   

   Geography_Spain  
0              0.0

In [17]:
#Scaling the input data
input_scaled=scaler.transform(input_df)
input_scaled

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [18]:
#PREDICTION
pred=model.predict(input_scaled)
pred

1/1 [==============================] - 0s 202ms/step


array([[0.04644547]], dtype=float32)

In [19]:
prediction_probability=pred[0][0]
prediction_probability

0.046445474

In [20]:
if prediction_probability>0.5:
    print("the customer is likely to churn")
else:
    print("the customer is not likely to churn")

the customer is not likely to churn
